---
title: "Sales Report"
author: "Nathan Young"
date: "4/4/2021"
output:
  word_document:
    toc: yes
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
```

## Data Import

```{r import, echo = FALSE, results = "hide", message = FALSE}
# import data
sales <- read_csv("data/property_sales.csv")

# first five rows of fake data
head(sales, n = 5)

# number of rows of fake data
total_sales <- nrow(sales)
```

A total of **`r total_sales`** property sales were imported from `property_sales.csv`.

```{r filter-dwellings, include = FALSE, }
# keep just "Dwelling" sales
dwelling_sales <- filter(sales,
  property_class == "Dwelling")

# percentage of sales that are dwellings
percent_dwelling <- (nrow(dwelling_sales) / total_sales) * 100
```

Of all the sales, `r round(percent_dwelling, 1)`% were dwellings.

## Dwelling Sales by Neighborhood

```{r summary, echo = FALSE}
# average price by neighborhood
dwelling_summary <- dwelling_sales %>%
  group_by(neighborhood) %>%
  summarize(
    n_sales = n(),
    mean_price = mean(sales_price),
    median_price = median(sales_price)
  ) %>%
  arrange(median_price)

# save output to disk
write_csv(dwelling_summary, "results/dwelling_summary.csv")

dwelling_summary %>% kable()
```


```{r plot, echo = FALSE, message = FALSE}
# plot all sale prices by neighborhood
dwelling_sales %>%
ggplot(aes(sales_price)) +
  geom_histogram() +
  scale_x_log10(labels = scales::label_dollar()) +
  facet_wrap(~neighborhood, scale = "free_y") +
  labs(
    x = "Sales price",
    y = "Number of sales"
  )

# save plot to disk
ggsave("results/sales_historgram.png", width = 8, height = 4.5)
```
